---
- hosts: localhost
  roles:
  - pre.

# init is not needed if you're only running on localhost!
- hosts: localhost
  vars:
    # Host_vars
    ansible_become_password: u
    ansible_user: "{{lookup('ansible.builtin.env', 'USER')}}"

  roles:
  - Go
